// CASOFFINDER — enumerate a guide's genome-wide off-target sites with Cas-OFFinder v3
// (mismatches + DNA/RNA bulges, done natively — no separate wrapper). Emits the v3 table
// (Id, Bulge Type, crRNA, DNA, Chromosome, Location, Direction, Mismatches, Bulge Size) that
// bin/combine_offtarget_results.py parses. CPU device ('C'), so no GPU is required.
process CASOFFINDER {
    tag "${meta.id}"
    label 'process_medium'
    container "ghcr.io/dhslab/docker-casoffinder-bulge:latest"

    input:
    tuple val(meta), val(spacer), val(pam)
    path twobit

    output:
    tuple val(meta), path("${meta.id}.casoffinder.txt"), emit: hits
    path "versions.yml",                                 emit: versions

    script:
    def mm  = params.offtarget_mismatches
    def bul = params.offtarget_bulges
    """
    # pocl (the CPU OpenCL driver) caches compiled kernels under \$HOME/.cache; under Apptainer's
    # --no-home the host HOME is absent/unwritable, which makes pocl report "No OpenCL devices
    # found". Point its cache at the (writable) task work dir so the 'C' device is available.
    export POCL_CACHE_DIR="\${PWD}/.pocl_cache"
    mkdir -p "\$POCL_CACHE_DIR"

    # Cas-OFFinder v3 native bulge input: genome, then "<pattern> <DNA bulge> <RNA bulge>", then
    # "<query> <mismatches>". Pattern masks the protospacer with N and appends the PAM;
    # the query is the spacer with N placeholders for the PAM bases (equal length to the pattern).
    SPACER=${spacer}
    PAM=${pam}
    PATTERN=\$(printf 'N%.0s' \$(seq 1 \${#SPACER}))\${PAM}
    QUERY=\${SPACER}\$(printf 'N%.0s' \$(seq 1 \${#PAM}))

    printf '%s\\n%s %s %s\\n%s %s\\n' \\
        "\$(readlink -f ${twobit})" "\$PATTERN" "${bul}" "${bul}" "\$QUERY" "${mm}" > casoffinder_input.txt

    cas-offinder casoffinder_input.txt C ${meta.id}.casoffinder.txt

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        cas-offinder: \$(cas-offinder 2>&1 | grep -oE 'Cas-OFFinder [0-9][0-9.a-z]*' | head -1 || echo NA)
    END_VERSIONS
    """

    stub:
    """
    printf '##Generated by Cas-OFFinder (stub)\\n#Id\\tBulge Type\\tcrRNA\\tDNA\\tChromosome\\tLocation\\tDirection\\tMismatches\\tBulge Size\\n' > ${meta.id}.casoffinder.txt
    touch versions.yml
    """
}
